[tool.poetry]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <No Email Provided>"]

[tool.poetry.dependencies]
python = "^3.13"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
pytest = "^8.3.3"
mypy = "^1.11.2"
isort = "^5.13.2"
pre-commit = "^3.8.0"
pytest-cov = "^5.0.0"
ruff = "^0.6.5"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.masonry.api"
